#!/bin/bash

# Dapp Modernization Script
# Generated by MCP Server Analyzer

set -euo pipefail

echo "🚀 Starting dapp modernization process..."

if ! command -v forge >/dev/null 2>&1; then
	echo "❌ forge not found on PATH. Please install Foundry first (e.g., curl -L https://foundry.paradigm.xyz | bash && foundryup), then rerun this script."
	exit 1
fi

# Install OpenZeppelin Contracts (idempotent)
echo "Installing OpenZeppelin..."
forge install OpenZeppelin/openzeppelin-contracts || true

# Update Solidity version
echo "Updating Solidity version in contracts..."
find . -name "*.sol" -type f -exec sed -i.bak "s/pragma solidity.*$/pragma solidity ^0.8.20;/g" {} \;
find . -name "*.sol.bak" -type f -delete

# Compile contracts
echo "Compiling contracts..."
forge build

# Run tests
echo "Running tests..."
forge test

echo "✅ Modernization complete!"
