#!/bin/bash

# Dapp Modernization Script
# Generated by MCP Server Analyzer

echo "🚀 Starting dapp modernization process..."

# Install Foundry
echo "Installing Foundry..."
curl -L https://foundry.paradigm.xyz | bash
foundryup

# Install OpenZeppelin Contracts
echo "Installing OpenZeppelin..."
forge install OpenZeppelin/openzeppelin-contracts

# Update Solidity version
echo "Updating Solidity version in contracts..."
find . -name "*.sol" -type f -exec sed -i "s/pragma solidity.*$/pragma solidity ^0.8.20;/g" {} \;

# Compile contracts
echo "Compiling contracts..."
forge build

# Run tests
echo "Running tests..."
forge test

echo "✅ Modernization complete!"
